
FROM node:20-alpine AS build
WORKDIR /app


COPY package.json package-lock.json* ./


RUN npm ci --only=production=false

COPY . .
RUN npm run build


FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

# Use the default nginx command
CMD ["nginx", "-g", "daemon off;"]
